language: d
d:
  - dmd
  - dmd-2.086.1
  - dmd-2.085.1
  - dmd-2.084.1
  - dmd-2.083.1
  - dmd-2.082.1
  - dmd-2.081.1
  - dmd-2.080.1
  - dmd-2.079.1
  - dmd-2.078.1
  - dmd-2.077.1
  - dmd-2.076.1
  - dmd-2.075.1
  - dmd-2.074.1
  - dmd-2.073.1
  - dmd-2.072.1
  - dmd-2.071.1
  - dmd-2.070.1
  - dmd-2.068.2
  - dmd-2.067.1
  - dmd-2.066.1
  - gdc
  - ldc

script: ./travis.sh

sudo: false
addons:
  apt:
    packages:
    - libcairo2
    - libcairo2-dev
